flowchart TD
    User(["Usuario"])
    Librarian(["Bibliotecário"])

    subgraph SB["Sistema da Biblioteca"]
    App["App do Usuário"]
    Backoffice["App do Bibliotecário"]
    Server["API"]
    DB[("Banco de Dados")]
    end

    Email["Serviço de e-mail"]

    User -->|pesquisa e empresta| App
    Librarian -->|Gerencia Livro| Backoffice
    App -->|Chama API| Server
    Backoffice -->|Chama API| Server
    Server -->|Lê e grava|DB
    Server --->|Monitora e notifica| Email